### ISSUE TITLE
Alternative output of result name in GNR [Request]

### ISSUE THREAD

**Issue by Alectoria** [GlobalNamesArchitecture/gni#43]
Right now, GNR produces two outputs of matched names: (1) the entire taxon name incl. author and (2) the canonical form. For example, for taxon 'Stipa pennnata var. anomala, you get: (1) 'Stipa pennata var. anomala (P.A.Smirn.) Tzvelev' and (2) 'Stipa pennata anomala'. 

I would like to request a third output, that includes taxonomic abbreviations (e.g. 'var', 'subsp') but not author names. Using the example above, this would be (3) 'Stipa pennata var. anomala'.

Some biological databases use the full taxon name (incl. abbreviations) but not the author name. Having this feature would help facilitate data merging among databases with the taxon name as a key variable.

**Comment by dimus** [comment]
Good point, I can do that

**Comment by dimus** [comment]
This issue depends on new functionality in biodiversity parser (v3.4.0). Parser can now add ranks to canonicals as an 'afterthought' which  will allow to make a flag of returning canonical names with or without infraspecific ranks

**Comment by dimus** [comment]
For API it is possible now to have canonicals with ranks --

**Comment by dimus** [comment]
Let me know if it solves your particular usecase

**Comment by Alectoria** [comment]
@dimus Yes, it did solve the issue. Thanks again!

**Comment by dimus** [comment]
:+1:
